### PR TITLE
Add rerendered entries for python 3.5

### PR DESCRIPTION
**Pull request by pmlandwehr**
New, rerendered entries that will *actually* test the py 3.5.patch...

### CODE REVIEW

**Comment by pmlandwehr** [comment]
Close/reopen because only Travis CI died and the build is working locally.

**Comment by pmlandwehr** [comment]
Well, dang.

**Comment by pmlandwehr** [comment]
O

**Comment by pmlandwehr** [comment]
One more close/reopen, because this is very strange.

**Comment by ocefpaf** [comment]
The problem is with the patch:

```shell
Applying patch: '/Users/travis/build/conda-forge/cmd2-feedstock/recipe/python35-compat.patch'
can't find file to patch at input line 3
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|--- a/cmd2.py
|+++ b/cmd2.py
--------------------------
File to patch: 
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
The build has been terminated
```

If you remove the `a/` and `b/` from [here](https://github.com/pmlandwehr/cmd2-feedstock/blob/2b1978f0fda3669a68105c5105fdfd1953434460/recipe/python35-compat.patch#L1-L2) the patch should apply cleanly.

PS: You can re-start the CIs instead of opening and closing the PR. You are registered as the maintainer of the feedstock.

**Comment by pmlandwehr** [comment]
Well I'll be.

**Pull request merged**
